// Generated by https://quicktype.io
import { IUser } from "./user";
import { ICommunity } from './community';
import { IComment } from "./comment";

export interface IPost {
	_id:         string;
	title:       string;
	description: string;
	user:        IUser;
	community:   ICommunity;
	comments:    IComment[];
	interactions: IInteractions;
	status:     boolean;
	createdAt:   string;
	updatedAt:   string;
}

export interface IInteractions{
	id?: string;
	likes: IUser[];
	dislikes: IUser[];
}