// Generated by https://quicktype.io
import { IUser } from "./user";

export interface IPost {
	createdAt:   string;
	description: string;
	title:       string;
	updatedAt:   string;
	user:        IUser;
	_id:         string;
}
